### ISSUE TITLE
Fix race condition during unload of integration when bulb is offline

### ISSUE THREAD

**Issue by bdraco** [sbidy/pywizlight#106]
This doesn't cause a user visible user but does generate log spam

```
2022-02-07 22:21:46 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pywizlight/bulb.py", line 353, in _async_send_register
    await self.sendUDPMessage(message)
  File "/usr/local/lib/python3.9/site-packages/pywizlight/bulb.py", line 568, in sendUDPMessage
    self.transport.sendto(data, (self.ip, self.port))
AttributeError: 'NoneType' object has no attribute 'sendto'
```

If the integration is unloaded right in the middle of a send retry when a device is offline, the transport can be deleted out from under it.  We need to guard here to make sure `self.transport` is not None

**Comment by bdraco** [comment]
I'll work on fixes for these. I'm doing testing as new devices show up and then I will aggregate a bunch of fixes.  So far I haven't found anything that actually breaks so all minor fixups 👍
