### ISSUE TITLE
Issue with DNS lookup in sendUDPMessage

### ISSUE THREAD

**Issue by sbidy** [sbidy/pywizlight#109]
Entered DNS name in Config Flow: wiz-22af76

Issue: the `class DatagramTransport(BaseTransport)` does not accept dns names as addr parameter `def sendto(self, data, addr=None)`

Exception:
```python
2022-02-08 17:43:30 ERROR (MainThread) [homeassistant.components.wiz.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/workspaces/core/homeassistant/components/wiz/config_flow.py", line 144, in async_step_user
    mac = await bulb.getMac()
  File "/usr/local/lib/python3.9/site-packages/pywizlight/bulb.py", line 518, in getMac
    await self.getBulbConfig()
  File "/usr/local/lib/python3.9/site-packages/pywizlight/bulb.py", line 524, in getBulbConfig
    resp = await self.sendUDPMessage(message)
  File "/usr/local/lib/python3.9/site-packages/pywizlight/bulb.py", line 569, in sendUDPMessage
    self.transport.sendto(data, (self.ip, self.port))
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 1040, in sendto
    raise ValueError(
ValueError: Invalid address: must be None or ('192.168.178.53', 38899)
```

**Comment by bdraco** [comment]
I think for this case let's resolve the name in Home Assistant using `loop.getaddrinfo()` and set the ip address in the config entry, and let discovery handle updates

**Comment by sbidy** [comment]
It is more a HASS related issue and will not be fixed.
In HASS we should use the IP only. For this library, only IPs are accepted for the `wizlight` class.
