### ISSUE TITLE
`Exception ignored` when trying to get state of a bulb.

### ISSUE THREAD

**Issue by Luuk34** [sbidy/pywizlight#132]
D:\TEMP>python -m pywizlight.cli --version
python -m pywizlight.cli, version 0.5.10

D:\TEMP>python -m pywizlight.cli state --ip 192.168.---.71
Get the state from 192.168.---.71
{'mac': 'd8----------', 'rssi': -42, 'src': '', 'state': True, 'sceneId': 11, 'temp': 2700, 'dimming': 20}
Exception ignored in: <function wizlight.__del__ at 0x00000236711F4550>
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\pywizlight\bulb.py", line 743, in __del__
    self.loop.call_soon_threadsafe(self._async_close)
  File "C:\Python310\lib\asyncio\base_events.py", line 790, in call_soon_threadsafe
    self._check_closed()
  File "C:\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000236710E2CB0>
Traceback (most recent call last):
  File "C:\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Python310\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "C:\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by Luuk34** [comment]
Same problem when using `on` or `off`

D:\TEMP>python -m pywizlight.cli on --ip 192.168.---.71
Kelvin for temperature. [3000]:
Set the brightness value 0-255 [128]:
Turning on 192.168.---.71
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001ABD1502CB0>
Traceback (most recent call last):
  File "C:\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Python310\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "C:\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

D:\TEMP>python -m pywizlight.cli off --ip 192.168.---.71
Turning off 192.168.---.71
Exception ignored in: <function wizlight.__del__ at 0x000001D85DFD4550>
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\pywizlight\bulb.py", line 743, in __del__
    self.loop.call_soon_threadsafe(self._async_close)
  File "C:\Python310\lib\asyncio\base_events.py", line 790, in call_soon_threadsafe
    self._check_closed()
  File "C:\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001D85DEB2CB0>
Traceback (most recent call last):
  File "C:\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Python310\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "C:\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by Luuk34** [comment]
Thanks, just check (with version 0.5.12), and problem is solved.
