### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by spencerthayer** [sbidy/pywizlight#64]
When installing using `pip install pywizlight` I get the following error:

```bash
Collecting pywizlight
  Downloading pywizlight-0.3.4.tar.gz (11 kB)
    ERROR: Command errored out with exit status 1:
     command: /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-i4iV2H/pywizlight/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-i4iV2H/pywizlight/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/tmp/pip-install-i4iV2H/pywizlight/pip-egg-info
         cwd: /private/tmp/pip-install-i4iV2H/pywizlight/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-install-i4iV2H/pywizlight/setup.py", line 11
        def get_version() -> str:
                          ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by sbidy** [comment]
Hey, you are using python27 which is not supported for this library. Please use python 3.7 or newer.

Python is, as fare I know, out of support since 2020.
